### ISSUE TITLE
Dev branch crashes on startup

### ISSUE THREAD

**Issue by prokoudine** [momentarylapse/tsunami#3]
```
Reading symbols from /opt/tsunami/bin/tsunami...
(gdb) run
Starting program: /opt/tsunami/bin/tsunami 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
terminate called after throwing an instance of 'FileError'

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Нет такого файла или каталога.
(gdb) bt
#0  0x00007ffff67a83eb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6787899 in __GI_abort () at abort.c:79
#2  0x00007ffff6b655f6 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6b719ec in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6b71a47 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6b71ca9 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005555555a0bb2 in FileCreateText(string const&) (filename=...) at ../src/lib/file/../base/base.h:58
#7  0x000055555562cea4 in msg_init(string const&, bool) (force_filename=..., verbose=true) at ../src/lib/file/msg.cpp:63
#8  0x000055555562cea4 in msg_init(string const&, bool) (force_filename=..., verbose=verbose@entry=true) at ../src/lib/file/msg.cpp:53
#9  0x000055555564126c in hui::Application::Application(string const&, string const&, int) (this=<optimized out>, app_name=..., def_lang=..., flags=1)
    at ../src/lib/hui/../base/strings.h:82
#10 0x0000555555844c03 in Tsunami::Tsunami() (this=0x555555969630) at ../src/Tsunami.cpp:44
#11 0x000055555584791a in hui_main(Array<string> const&) (arg=...) at ../src/Tsunami.cpp:250
#12 0x00005555555d7158 in main(int, char**) (NumArgs=<optimized out>, Args=<optimized out>) at ../src/lib/hui/hui.cpp:127
(gdb) 

```

**Comment by momentarylapse** [comment]
thanks a lot for testing! (I didn't expect anyone to try out, sorry not seeing your message earlier...)

I tried to fix it in the current devel branch.

The program expected to be installed somewhere in /usr/ or /usr/local/ and got confused by /opt/. How did you install it? Using meson/ninja install? Also which system do you use?

You can also run the program without installing it. After building, you can run the executable from within the root of the repository, i.e. if you've built it with meson, you might have a "build" directory and you can run
 ./build/tsunami
